#pragma once
// This file has been generated by zoltan (https://github.com/jac3km4/zoltan)

#define ZOLTAN_STRINGISE(N) #N
#define ZOLTAN_EXPAND_THEN_STRINGISE(N) ZOLTAN_STRINGISE(N)
#define __LINE_STR__ ZOLTAN_EXPAND_THEN_STRINGISE(__LINE__)

#define CreateStaticEffect_Addr 0x14A19A0

#include <RED4ext/RED4ext.hpp>
#include <RED4ext/Relocation.hpp>

RED4EXT_INLINE uint64_t CreateStaticEffect(RED4ext::game::EffectSystem* a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5) {
    using CreateStaticEffect_t = uint64_t (*)(RED4ext::game::EffectSystem*, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t);
    RED4ext::RelocFunc<CreateStaticEffect_t> call(CreateStaticEffect_Addr);
    return call(a0, a1, a2, a3, a4, a5);
}

